server-name: "reze (home-server)"
server-image: "/src/img/reze.png"
port: "6969"
corsheader: "*"
internalauth: "4t2@.a51j:u)s=n|yg9^vio!>k,7*-f0c~rwz6?<bme3#/;q$+%8&h_xp(d"
refresh-interval: "5m"
return-only-running: true
servers:
  - name: "Minecraft"
    method: systemd
    unit: minecraft.service
  - name: "7 Days to Die: Undead Legacy"
    method: process
    match: "7DaysToDieServer.x86_64"
  - name: "home-server"
    method: port
    port: 1759